### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by NielsPilgaard** [Tamaized/AoV#76] opened 2018-05-10 07:53 UTC
Hey, a user of mine found a crash caused by AoV: https://pastebin.com/t5pqZrMv

AoV-1.12-0.8.12
Forge 1.12.2-14.23.3.2673

**Comment by Tamaized** [comment] 2018-05-24 16:11
Duplicate of #69

**Closed as completed by Tamaized** 2018-05-24 16:11 UTC
