### ISSUE TITLE
Conflict between AoV and Wizardry

### ISSUE THREAD

**Issue by Tyrius1** [Tamaized/AoV#115] opened 2019-03-13 22:14 UTC
https://minecraft.curseforge.com/projects/dogma Conflict between AoV and Wizardry causing Wizardry codex to not load properly. When removing AoV codex works as intended.

**Comment by murapix** [comment] 2019-03-13 22:19
This has been reported a couple times in TeamWizardry/Wizardry#223

**Comment by Tamaized** [comment] 2019-03-13 22:29
My initial guess was a stencil buffer conflict but that doesn't seem to be the case unless i'm mistaken. Other than that I have no idea where the issue is as it's a bit difficult for me to navigate their codebase across the libs and such (and it's written in kotlin bleh)

if someone wants to go digging feel free.

**Comment by Tamaized** [comment] 2019-03-15 23:43
Found the issue, it was indeed my first hunch, a stencil buffer conflict.

Working on a fix~

**Comment by Tamaized** [comment] 2019-03-16 04:02
Should be fixed in version 0.11.4

leaving this open until i merge the fix into my 1.13 branch

**Closed as completed** 2019-03-25 16:34 UTC
Labels: Bug
